modLoader="javafml"
loaderVersion="[28,)"
logoFile="logo.png"

[[mods]]
modId="rys"
version="${mod_version}"
displayName="Ready Your Shovels"
credits="${mod_credits}"
authors="${mod_authors}"
description='''
${mod_description}
'''

[[dependencies.rys]]
	modId="forge"
	mandatory=true
	versionRange="[28,)"
	ordering="NONE"
	side="BOTH"

[[dependencies.rys]]
	modId="minecraft"
	mandatory=true
	versionRange="[1.14.4]"
	ordering="NONE"
	side="BOTH"
