modLoader="javafml"
loaderVersion="[28,)"
logoFile="logo.png"

[[mods]]
modId="rys"
version="0.1.8"
displayName="Ready Your Shovels"
credits="Axoladdy"
authors="camiloss20"
description='''
Ready Your Shovels
'''

[[dependencies.rys]]
	modId="forge"
	mandatory=true
	versionRange="[28,)"
	ordering="NONE"
	side="BOTH"

[[dependencies.rys]]
	modId="minecraft"
	mandatory=true
	versionRange="[1.14.4]"
	ordering="NONE"
	side="BOTH"
